name: Certora Prover Submission Workflow
description: |-
  This workflow submits Certora Prover jobs on the specified configurations. Once all
  jobs are successfully submitted, it will add a pending commit status to the commit.
  This status will be periodically updated with verification results of the jobs, along
  with the verification summary comment on the pull request.

  For more information, please visit https://github.com/certora/certora-run-action.

on:
  pull_request:
    branches:
      - master
      - certora/specs
  workflow_dispatch:

jobs:
  certora_run_submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install foundry, needed for prover path resolution
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Run Certora munge script
      - name: Certora munge
        run: ./certora/scripts/patch.sh

      # Submit verification jobs to Certora Prover
      - name: Submit verification jobs to Certora Prover
        uses: Certora/certora-run-action@v2
        with:
          # Add your configurations as lines, each line is separated.
          # Specify additional options for each configuration by adding them after the configuration.
          configurations: |-
            certora/confs/Balances.conf
            certora/confs/ConsistentState.conf
            certora/confs/ConsistentStateExtras.conf
            certora/confs/ConsistentStateExtras2.conf
            certora/confs/ConsistentStateExtras3Sanity.conf
            certora/confs/Enabled.conf
            certora/confs/Immutability.conf
            certora/confs/Liveness.conf
            certora/confs/PendingValues.conf
            certora/confs/Range.conf
            certora/confs/Reentrancy.conf
            certora/confs/Reverts.conf
            certora/confs/Roles.conf
            certora/confs/Timelock.conf
            certora/confs/TimelockRemovableTime.conf
            certora/confs/LostAssets.conf
            certora/confs/Conversions.conf
            certora/confs/ERC4626.conf
            certora/confs/Solvency.conf
            certora/confs/SolvencyInternal.conf
          solc-versions: 0.8.17 0.8.26
          job-name: "Verified Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
